Improve user experience of sidebar navigation
unicef/inventory pull request #110
Opened 2021-12-23 16:45 UTC by Idadelveloper

@jwflory this addresses [#27](https://github.com/unicef/inventory-hugo-theme/issues/27)

It looks like this:
![improved-sidebar](https://user-images.githubusercontent.com/56026636/147269398-a837e932-a7d9-4772-a5a5-a6653d6174ea.png)

2021-12-23 22:27 UTC, jwflory requested changes
Following up from stand-up, we will land the sidebar partial into the theme repository to ease future integration of the team profiles feature into the theme.

I tried to replicate the results in the screenshot, but I was unable to. I had different results when I cloned down the repo:

![Screenshot of Cohorts page on a 1080p monitor](https://user-images.githubusercontent.com/4721034/147296022-f7c01c38-7917-4a1c-b8df-a84e622a8c8b.png "Screenshot of Cohorts page on a 1080p monitor")

![Screenshot of Blockchain Cohort page on a 1080p monitor](https://user-images.githubusercontent.com/4721034/147296086-05a948d2-8054-445e-b758-fa4ae184ee06.png "Screenshot of Blockchain Cohort page on a 1080p monitor")

![Screenshot of Cohorts page on a 640p viewport](https://user-images.githubusercontent.com/4721034/147296142-e73ab2b6-a6ad-4c85-9c72-a74a71cb13a3.png "Screenshot of Cohorts page on a 640p viewport")

Are there corresponding changes inside the theme that should go with this PR? I would guess something is different in the stylesheets between us.

2021-12-27 17:17 UTC, Idadelveloper commented
@jwflory the reason your results are different is that I made some changes as well in the CSS file of the theme. Will send a PR.

2021-12-31 16:52 UTC, Idadelveloper commented
@jwflory I moved the  sidebar partial to the theme https://github.com/unicef/inventory-hugo-theme/pull/45

2022-01-05 21:38 UTC, jwflory commented
Blocking this on unicef/inventory-hugo-theme#45.

2022-01-10 14:24 UTC, jwflory commented
@Idadelveloper What do we want to do with this Pull Request since unicef/inventory-hugo-theme#45 was merged?

2022-01-10 16:49 UTC, jwflory commented
Rebased on commit 4bfd52cbabb6a1d1ccd2fdf97b9d673e14c57150.

2022-01-14 14:48 UTC, Idadelveloper commented
@jwflory this PR is supposed to address the weird sidebar of the cohort pages

2022-01-18 16:00 UTC, jwflory commented
Some quick feedback, but the sidebars do not seem to share all of the same code. The dropdowns do not have a scrollbar and there seems to be extra whitespace at the end of the sub-menu. I don't see that issue with another section on the site, like the Meta category.

![Cohorts sidebar menu.](https://user-images.githubusercontent.com/4721034/149972674-37bc4654-e9f8-4152-9e1f-c56af65bdcf8.png "Cohorts sidebar menu.")

![Category sidebar menu. This is the Meta category.](https://user-images.githubusercontent.com/4721034/149972875-fa0a2ae7-4bfc-4f9d-a99b-12ccaf84ef34.png "Category sidebar menu. This is the Meta category.")

@Idadelveloper Any idea why this is? I can't debug at the moment.

2022-01-19 11:47 UTC, Idadelveloper commented on layouts/partials/types.html
> +        {{ partial "sidebar.html" . }}
@jwflory I don't think the real issue is from the classes in the several `<div>` tags. [Here](https://github.com/unicef/inventory-hugo-theme/blob/3ad93312b76604d5b665deffb29644ed4fa4e2a5/layouts/partials/default.html#L6)'s where we have the sidebar for the other pages and it is as well within the same tags this one is in.
Or am I missing the point?

2022-01-19 12:15 UTC, jwflory commented
I'm not at my keyboard this moment, but I would use the developer tools 
in the browser to compare the two sidebars. I know Firefox can quickly 
see CSS class inheritance from the developer tools menu.
-- 
Cheers,
Justin W. Flory (he/him)
https://jwf.io
Sent via FairEmail

Jan 19, 2022 12:47:42 Ida Delphine ***@***.***>:

> 
> Here[https://github.com/unicef/inventory-hugo-theme/blob/3ad93312b76604d5b665deffb29644ed4fa4e2a5/layouts/partials/default.html#L6]'s

2022-01-25 14:45 UTC, jwflory commented
The cohorts page now has the fixed sidebar, but the sidebar disappears completely on individual profile pages. Not sure what the root cause is, but I will try to dig in and investigate why this is.

2022-02-03 11:04 UTC, jwflory approved these changes

2022-02-03 11:05 UTC, merged